# Generated by Django 5.0.3 on 2024-07-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0002_remove_produto_preco_produto_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadecompra',
            name='produto_nome',
            field=models.CharField(default='Produto desconhecido', max_length=100),
        ),
    ]
