# Generated by Django 5.0.3 on 2024-07-22 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0003_listadecompra_produto_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listadecompra',
            old_name='preco',
            new_name='preco_unitario',
        ),
    ]
